fail_fast = true

[[repos]]
repo = "builtin"
hooks = [
  {id = "check-added-large-files"},
  {id = "check-case-conflict"},
  {id = "check-executables-have-shebangs"},
  {id = "check-merge-conflict"},
  {id = "end-of-file-fixer"},
  {id = "fix-byte-order-marker"},
  {id = "mixed-line-ending", args = ["--fix=lf"]},
  {id = "trailing-whitespace", args = ["--markdown-linebreak-ext=md"]},
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.4"
hooks = [
  {id = "ruff-check", args = ["--fix"]},
  {id = "ruff-format"},
]
